
name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.0'

    - name: Build
      run: go build -v -o code-review main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-review
        path: code-review
